### ISSUE TITLE
Changes to Limit Break bar for pulling CPU and GPU temps with latest changes to HWiNFO

### ISSUE THREAD

**Issue by WingedAsarath** [enkille/ffxiv-rainmeter#1]
Hi! I love this rainmeter skin. I previously updated my old personal skin to account for changes to HWiNFO which means that CPU and GPU temps need to be pulled directly from manually created registry entries. The official rainmeter post about it is here for reference: [https://docs.rainmeter.net/tips/hwinfo/](https://docs.rainmeter.net/tips/hwinfo/)

I've tried editing the .ini file from here and applying some of my previous code, and while I can get the temperatures pulling through correctly, the bars now permanently show full or near-full, and I'm not sure if there's any changes that need making to scale them better with the new data?

I've attached my modified .ini file to this post :)

[LimitBreak-Temps.zip](https://github.com/enkille/ffxiv-rainmeter/files/7719601/LimitBreak-Temps.zip)

![image](https://user-images.githubusercontent.com/61755582/146193770-f969205f-871f-4f57-b308-c812748b67aa.png)

Any help from anyone would be greatly appreciated!

**Comment by enkille** [comment]
Hello! I'm currently traveling but I will be able to look at this next week. Thanks for your interest in my project!

**Comment by enkille** [comment]
Found the issue -- You just have to re-add the MinValue and MaxValue keys in the ini for both meters.

```
[MeasureGPUTemp]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw#GPUTempIndex#
MinValue=30
MaxValue=100

[MeasureCPUTemp]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw#CPUTempIndex#
MinValue=30
MaxValue=100
```

I set these to 30-100 which seems like a decent range. Let me know how this works out for you.

**Comment by enkille** [comment]
Pushed a commit to add HWiNFO as a variant to the limit break bars so it'll still work with Speedfan as well.
